block-list-secret-scan: []
branch: main
directory:
  - .
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - all
mask: []
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_DOCKER_2
  - CKV_DOCKER_3
  - CKV_DOCKER_8
summary-position: top
